[2019-03-30 17:44:41,760]WARNING:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/liu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/liu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
[2019-03-30 17:44:41,761]INFO:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest
[2019-03-30 17:44:41,925]INFO:URL being requested: POST https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json
[2019-03-30 17:44:42,151]INFO:Event created for [Justin Nordeman] for course [Calculus II] from [2019-03-26T09:30:00] to [2019-03-26T10:30:00]
[2019-03-30 17:49:07,294]WARNING:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/liu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/liu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
[2019-03-30 17:49:07,295]INFO:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest
[2019-03-30 17:49:07,463]INFO:URL being requested: POST https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json
[2019-03-30 17:49:07,702]INFO:Event created for [Justin Nordeman] for course [Calculus II] from [2019-03-26T09:30:00] to [2019-03-26T10:30:00]
[2019-03-30 17:50:53,611]INFO:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest
[2019-03-30 17:50:53,826]INFO:URL being requested: POST https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json
[2019-03-30 17:50:54,062]INFO:Event created for [Justin Nordeman] for course [Calculus II] from [2019-03-26T09:30:00] to [2019-03-26T10:30:00]
[2019-03-30 17:52:28,915]INFO:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest
[2019-03-30 17:52:29,081]INFO:passed here 1
[2019-03-30 17:52:29,090]INFO:URL being requested: POST https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json
[2019-03-30 17:52:29,310]INFO:passed here 2
[2019-03-30 17:52:29,310]INFO:Event created for [Justin Nordeman] for course [Calculus II] from [2019-03-26T09:30:00] to [2019-03-26T10:30:00]
